package moviedb;

import java.util.List;
import javax.swing.JCheckBox;
import moviedb.models.Movie;
import moviedb.models.Contributor;
import moviedb.service.MovieDBService;

/**
 *
 * @author enzma
 */
public class MovieDetailsGUI extends javax.swing.JDialog {

    private final int id;
    private Movie m;

    private final MovieDBService service;

    /**
     * Creates new form MovieDetailsGUI
     *
     * @param id
     * @param service
     * @param parent
     */
    public MovieDetailsGUI(int id, MovieDBService service, javax.swing.JFrame parent) {
        super(parent, true);
        
        this.id = id;
        this.service = service;

        initComponents();

        refresh();
    }

    private void refresh() {
        service.refresh();
        m = service.getMoviesByID(id);

        txfTitle.setText(m.getTitle());
        txfReview.setText(String.format("%.1f", m.getAverageRating()));
        txfStudio.setText(service.getStudioByID(m.getStudioID()).getName());
        txaDescription.setText(service.addLineBreaks(m.getDescription(), 70));

        List<Contributor> contributors = m.getContributors();
        StringBuilder builder = new StringBuilder();

        for (Contributor contributor : contributors) {
            String personName = service.getPersonByID(contributor.getPersonID()).getName();

            builder.append(contributor.getRole());
            builder.append(":\t\t");
            builder.append(personName);
            builder.append("\n");
        }

        txaContributions.setText(builder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblStudio = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();
        txfStudio = new javax.swing.JTextField();
        txfReview = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        txfTitle = new javax.swing.JTextField();
        btnAddReview = new javax.swing.JButton();
        lblContributions = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaContributions = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        btnSafe = new javax.swing.JButton();
        checkEnabled = new javax.swing.JCheckBox();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setText("Title");

        lblDescription.setText("Description");

        lblStudio.setText("Studio");

        lblRating.setText("Rating");

        txfStudio.setEditable(false);
        txfStudio.setText("jTextField1");

        txfReview.setEditable(false);
        txfReview.setText("jTextField1");

        txaDescription.setEditable(false);
        txaDescription.setColumns(20);
        txaDescription.setRows(5);
        jScrollPane1.setViewportView(txaDescription);

        txfTitle.setEditable(false);
        txfTitle.setText("jTextField3");

        btnAddReview.setText("Add Review");
        btnAddReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReviewActionPerformed(evt);
            }
        });

        lblContributions.setText("Contributions");

        txaContributions.setEditable(false);
        txaContributions.setColumns(20);
        txaContributions.setRows(5);
        jScrollPane2.setViewportView(txaContributions);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSafe.setText("Safe changes");
        btnSafe.setEnabled(false);
        btnSafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSafeActionPerformed(evt);
            }
        });

        checkEnabled.setText("enable changes");
        checkEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEnabledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRating)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudio)
                                    .addComponent(lblTitle)
                                    .addComponent(lblDescription)
                                    .addComponent(lblContributions))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(checkEnabled)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                            .addComponent(txfTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfStudio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnSafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txfReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddReview)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudio)
                            .addComponent(txfStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContributions))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRating)
                            .addComponent(txfReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAddReview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSafe)
                    .addComponent(btnClose)
                    .addComponent(checkEnabled))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReviewActionPerformed
        NewReviewGUI frame = new NewReviewGUI(id, service, this);
        frame.setVisible(true);
        
        refresh();
    }//GEN-LAST:event_btnAddReviewActionPerformed

    private void btnSafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSafeActionPerformed
        service.editMovie(id, txfTitle.getText(), txaDescription.getText().replace("\n", "")); 
        service.refresh();
        refresh();
    }//GEN-LAST:event_btnSafeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void checkEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEnabledActionPerformed
        JCheckBox cb = (JCheckBox) evt.getSource();

        boolean selected = cb.isSelected();

        txfTitle.setEditable(selected);
        txaDescription.setEditable(selected);
        btnSafe.setEnabled(selected);
    }//GEN-LAST:event_checkEnabledActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddReview;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSafe;
    private javax.swing.JCheckBox checkEnabled;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblContributions;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblStudio;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txaContributions;
    private javax.swing.JTextArea txaDescription;
    private javax.swing.JTextField txfReview;
    private javax.swing.JTextField txfStudio;
    private javax.swing.JTextField txfTitle;
    // End of variables declaration//GEN-END:variables
}
