package moviedb;

import moviedb.models.Review;
import moviedb.service.MovieDBService;

import javax.swing.*;

/**
 *
 * @author david.omoregie
 */
public class NewReviewGUI extends javax.swing.JDialog {

    private final int id;
    private final MovieDBService service;

    /**
     * Creates new form NewReview
     *
     * @param id
     * @param service
     * @param parent
     */
    public NewReviewGUI(int id, MovieDBService service, javax.swing.JFrame parent) {
        super(parent, true);

        this.id = id;
        this.service = service;
        initComponents();
    }

    public NewReviewGUI(int id, MovieDBService service, javax.swing.JDialog parent) {
        super(parent, true);

        this.id = id;
        this.service = service;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancle = new javax.swing.JButton();
        btnSafe = new javax.swing.JButton();
        lblRating = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCancle.setText("Cancel");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancle(evt);
            }
        });

        btnSafe.setText("Safe");
        btnSafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSafe(evt);
            }
        });

        lblRating.setText("Rating");

        lblUsername.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSafe)
                                .addGap(55, 55, 55)
                                .addComponent(btnCancle))
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRating)
                            .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblRating)
                .addGap(18, 18, 18)
                .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addGap(18, 18, 18)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSafe)
                    .addComponent(btnCancle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSafe(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSafe
        String textRating = txtRating.getText();
        String textUsername = txtUsername.getText();
        if (textRating.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a numeric value");
            return;
        }
        if ((!textRating.matches("[0-5]+") && textRating.length() > 2)) {
            JOptionPane.showMessageDialog(this, "Please enter a numeric value");
            return;
        }
        if (textUsername.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type a Username");
            return;
        }

        Review r = new Review(Integer.parseInt(txtRating.getText()), txtUsername.getText());
        service.addReview(r, id);
        JOptionPane.showMessageDialog(this, "Review safed");
        this.dispose();
    }//GEN-LAST:event_btnSafe

    private void btnCancle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancle
        dispose();
    }//GEN-LAST:event_btnCancle

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnSafe;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
